# SQLite. Versions 3.8.0 and up are supported.
#   gem install pg
#
#   Ensure the gem is defined in your Gemfile
#   gem 'pg'
#
development:
  adapter: postgresql
  database: mikuapp_dev
  username: skeletor
  password: 123
  encoding: unicode
  host: localhost
  pool: 5
  
  
test:
  adapter: postgresql
  database: mikuapp_test
  username: skeletor
  password: 123
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: mikuapp_production
  username: miku
  password: <%= ENV['MIKUAPP_DATABASE_PASSWORD'] %>


